#!/usr/bin/env bash

##########
# Common #
##########

# Show list of all installed packages (Debian)
# Credit: StackOverflow
alias list_packages='dpkg --get-selections | grep -v deinstall'


#####################
# Raspberry Pi ONLY #
#####################

if [ "$DISTRO" == 'Raspbian' ]; then
    alias pitemp='/opt/vc/bin/vcgencmd measure_temp'
fi
